### ISSUE TITLE
Can't run more than one query

### ISSUE THREAD

**Issue by diije** [antoineeripret/gsc_wrapper#9]
Hello!

I can't seem to be able to run more than one query in the same script.
If I try to run a second query, it'll end up with a `KeyError: 'rows'`.

Example script:

```python
import gscwrapper

account = gscwrapper.generate_auth(..., credentials=...)
webproperty = account[...]

report = (
    webproperty
    .query
    .range(start="2024-01-01", stop="2024-01-31")
    .filter("page", ..., "equals")
    .dimensions(['query'])
    .get()
)
print(report.show_data())

report2 = (
    webproperty
    .query
    .range(start="2024-01-01", stop="2024-01-31")
    .filter("page", ..., "equals")
    .dimensions(['query'])
    .get()
)
print(report2.show_data())
```

First report works fine, second ends up with:

```
Traceback (most recent call last):
  File "/.../essai.py", line 34, in <module>
    .get()
     ^^^^^
  File "/.../gscwrapper/query.py", line 163, in get
    total_rows += len(chunk['rows'])
                      ~~~~~^^^^^^^^
KeyError: 'rows'
```

This is obviously quite an issue for certain tasks I'd like to run 😬 
Any idea of a fix?

Thanks!

**Comment by antoineeripret** [comment]
Hi @diije, 

Thanks for raising the issue. 

It doesn't seem to come from having more than one report, as I've run successfully the following code: 


```python

r1 = (
    webproperty
    .query
    .range('2024-01-01','2024-01-02')
    .dimensions(['date'])
    .get()
    
)

r2 = (
    webproperty
    .query
    .range('2024-02-01','2024-02-02')
    .dimensions(['date'])
    .get()
    
)
```

It appears that the following line of code ... 

```python
#retrieve the data 
chunk = self.service.searchanalytics().query(siteUrl=self.webproperty, body=self.raw).execute()
total_rows += len(chunk['rows']) #code breaks here 
```
... is not returning a `dict` with a `rows` key. This is an issue that I realized I had in a previous version of the library, and I updated the library to use now the following code: 

`total_rows += len(chunk.get('rows', []))` which basically returns an empty list if the `rows` key is not found (it can happen if there is no more data to retrieve).  This was fixed in [this commit](https://github.com/antoineeripret/gsc_wrapper/commit/70b3cf5c011d247b55f4f685878d900e31eea65e#diff-9d3c6182b5b8755fe58b24ff9134f2e2e3f1c6fc8ca8451560fd35a25e9c5109). 

**Please ensure that you are using the last version of the library and let me know if the issue is still happening**. 

Thanks!

**Comment by diije** [comment]
@antoineeripret I upgraded the lib (btw, you might want to add an "upgrade" section to the readme ;)).
Changes the error, but I still have an error when the second `.get()` runs:

```
Traceback (most recent call last):
  File ".../essai.py", line 25, in <module>
    .get()
     ^^^^^
  File ".../gscwrapper/query.py", line 184, in get
    flattened
  File ".../pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'keys'
```

I might add that both queries should definitely return data!

**Comment by antoineeripret** [comment]
Hi @diije, 

I've managed to reproduce the issue. Let me explain a bit of the logic first to explain why you are getting this error. 

- When you call the `get()`method, a `while`loop is triggered 

```python 
while is_complete == False and limit_achieved == False:
```

The `limit_achieved` is `True`only if the number of rows retrieved is higher than what you define using the `limit()`method. If it is not defined (your case), the limit is infinite and this variable will always be `False`. 
The `is_complete`is `True` when the following code returns a `dict`with less than 25,000 records (the maximum we can get per call with the GSC API). 

The only way - I can think of - to trigger the error you had is if the following `ìf` statement is `True` during the first execution of the while loop. 

```python
if len(chunk.get('rows', []))<25000:
                is_complete = True
```

Which is what happens when you have no data or your filter is incorrect. For instance: 

```python 

(
    webproperty
    .query
    .range("2024-01-01","2024-01-31")
    .dimensions(['query'])
    #incorrect filter 
    .filter("country",'lweflkewjfl','equals')
    .get()
)

```

Which returned exactly the error you had in your last message. **To be fair, I should display a better error message, and I'll add it to the logic when we get to the bottom of your issue** and understand what is going on. 

Therefore: 

- Can you double-check that you indeed have data in GSC with the filters / range you specified? 
- If that's the case, can you please run the following code and copy here what you are getting (removing sensitive info, obviously)?  

```python
(
    webproperty
    .query
    .range("2024-01-01","2024-01-31")
    .dimensions(['query'])
    .filter("country",'lweflkewjfl','equals')
    .raw 
) 
```

Thanks!

**Comment by diije** [comment]
Hey!

> Can you double-check that you indeed have data in GSC with the filters / range you specified?  

I already did of course: in fact if I comment out the first report, the second runs OK.  
I tried adding a `.limit(5)` for the sake of it but it doesn't change the outcome: the second report doesn't work.

> If that's the case, can you please run the following code and copy here what you are getting (removing sensitive info, obviously)?  

Here's what I get:

```
{'startRow': 0, 'rowLimit': 25000, 'startDate': '2024-01-01', 'endDate': '2024-01-31', 'dimensions': ['query'], 'dimensionFilterGroups': [{'groupType': 'and', 'filters': [{'dimension': 'country', 'expression': 'lweflkewjfl', 'operator': 'equals'}]}]} 
```

**Comment by antoineeripret** [comment]
Hey @diije, 

It appears that you ran my code: 

```python 
(
    webproperty
    .query
    .range("2024-01-01","2024-01-31")
    .dimensions(['query'])
    .filter("country",'lweflkewjfl','equals')
    .raw 
) 
```
Based on that part 

`'filters': [{'dimension': 'country', 'expression': 'lweflkewjfl', 'operator': 'equals'}]`

I meant to run it with your filters / conditions applied and copy the result here.

Thanks.

**Comment by diije** [comment]
Haha we'll get there 😂 

Here's what I get:

```
{'startRow': 0, 'rowLimit': 25000, 'startDate': '2024-01-01', 'endDate': '2024-01-31', 'dimensionFilterGroups': [{'groupType': 'and', 'filters': [{'dimension': 'page', 'expression': 'page1', 'operator': 'equals'}]}], 'dimensions': ['query']}

{'startRow': 0, 'rowLimit': 25000, 'startDate': '2024-01-01', 'endDate': '2024-01-31', 'dimensionFilterGroups': [{'groupType': 'and', 'filters': [{'dimension': 'page', 'expression': 'page1', 'operator': 'equals'}, {'dimension': 'page', 'expression': 'page2', 'operator': 'equals'}]}], 'dimensions': ['query']}
```

It seems the filter isn't reset.


Meanwhile, I found a fix: if I don't set a `webproperty` but directly use the `account` object, both reports run correctly.
Ex:

```
report = (
    account["..."]
    .query
    .range(start="2024-01-01", stop="2024-01-31")
    .filter("page", "...", "equals")
    .dimensions(['query'])
    .get()
)
```

**Comment by concernedcitizen1231a** [comment]
I can confirm that the problem @diije is having does exist. Although it occurs when you run multiple reports simultaneously with the filters on, without them, it works just fine.

**Comment by antoineeripret** [comment]
@diije: 

Your second report should be empty ... 

`{'startRow': 0, 'rowLimit': 25000, 'startDate': '2024-01-01', 'endDate': '2024-01-31', 'dimensionFilterGroups': [{'groupType': 'and', 'filters': [{'dimension': 'page', 'expression': 'page1', 'operator': 'equals'}, {'dimension': 'page', 'expression': 'page2', 'operator': 'equals'}]}], 'dimensions': ['query']}`

... because conditions are merged with AND.  The `page` dimension cannot be equal to `page1` AND `page2`. The GSC APÎ doesn't allow OR statements, you should use a REGEX for that `(page1|page2)` with ìncludingRegex' as an operator. 

Could that be the root of your issue?

**Comment by antoineeripret** [comment]
@concernedcitizen1231a: please open a separate ticket with more context / info. Cannot solve an issue I'm unaware of and if removing filters solve it, it may be what I've stated in my last comment.

**Comment by concernedcitizen1231a** [comment]
Sorry! @antoineeripret 

I've edited my message for more context

**Comment by diije** [comment]
@antoineeripret I think that's mostly a "philosophy" issue 😄 

You're apparently considering that the second query should take the first one into account: this explains why filters aren't reset when running a second query on the same `webproperty`.
I want to run independant queries. 

I think the technical reason for this is that `query` is [an attribute of `Webproperty`](https://github.com/antoineeripret/gsc_wrapper/blob/7b905676974d84ccbfab89386222181dea824a11/gscwrapper/account.py#L82), not a method: thus, it's persistant.


As I said, not setting a `webproperty` object but rather using directly the `account` (or said differently, creating a new `Webproperty` instance each time) seems to work fine. You might want to add this to the documentation for future users ;)

**Comment by antoineeripret** [comment]
Aaaaah, got it ! And @concernedcitizen1231a you have the same issue! 

So, you should run: 

```python
r1 = (
    account['https://www.example.com/']
    .query
    .range("2024-01-01","2024-01-31")
    .dimensions(['query'])
    .filter("country",'fra','equals')
)

r2= (
     account['https://www.example.com/']
    .query
    .range("2024-01-01","2024-01-31")
    .dimensions(['query'])
    .filter("country",'hey','equals')
)
```

I can actually "fix" that by resetting the filters once a report has been downloaded. And both philosophies would work. I'll add it to the big release I'm working on right now, thanks for taking the time to raise the issue !! 

I'll leave it open until the fix is merged into the main branch.

**Comment by concernedcitizen1231a** [comment]
Appreciate it! 

The lib is awesome by the way - the predefined analyses are very useful. So keep up the good work!

**Comment by antoineeripret** [comment]
FYI, this is the fix: just before returning the `Report` object, filters are removed: 

```python 
#reset filter to prevent issue raised here https://github.com/antoineeripret/gsc_wrapper/issues/9 
self.raw.pop('dimensionFilterGroups',None)
```

Thanks @concernedcitizen1231a  and @diije ! Open source FTW!

**Comment by diije** [comment]
@antoineeripret just tried your fix and I can confirm this works too.
Thanks!

**Comment by antoineeripret** [comment]
Fixed.
